include: package:lints/recommended.yaml

analyzer:
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see https://dart.dev/tools/linter-rules
linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
